"""Add programacion table

Revision ID: 16c976d2801b
Revises: 9dbaafd9a28f
Create Date: 2025-10-07 02:59:01.054367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16c976d2801b'
down_revision = '9dbaafd9a28f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('set_reglas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_reglas_id'), 'set_reglas', ['id'], unique=False)
    op.create_table('programacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mc', sa.Boolean(), nullable=True, comment='Si se pudo agregar la canción'),
    sa.Column('numero_reloj', sa.String(length=10), nullable=False, comment='Número del reloj'),
    sa.Column('hora_real', sa.Time(), nullable=True, comment='Hora real de transmisión'),
    sa.Column('hora_transmision', sa.Time(), nullable=True, comment='Hora de transmisión'),
    sa.Column('duracion_real', sa.String(length=10), nullable=True, comment='Duración real (HH:MM:SS)'),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='Tipo de evento'),
    sa.Column('hora_planeada', sa.Time(), nullable=True, comment='Hora planeada'),
    sa.Column('duracion_planeada', sa.String(length=10), nullable=True, comment='Duración planeada (HH:MM:SS)'),
    sa.Column('categoria', sa.String(length=50), nullable=False, comment='Categoría del evento'),
    sa.Column('id_media', sa.String(length=50), nullable=True, comment='ID del media'),
    sa.Column('descripcion', sa.String(length=200), nullable=True, comment='Descripción del evento'),
    sa.Column('lenguaje', sa.String(length=20), nullable=True, comment='Idioma'),
    sa.Column('interprete', sa.String(length=100), nullable=True, comment='Intérprete/Artista'),
    sa.Column('disco', sa.String(length=100), nullable=True, comment='Disco/Álbum'),
    sa.Column('sello_discografico', sa.String(length=100), nullable=True, comment='Sello discográfico'),
    sa.Column('bpm', sa.Integer(), nullable=True, comment='Beats per minute'),
    sa.Column('año', sa.Integer(), nullable=True, comment='Año de lanzamiento'),
    sa.Column('difusora', sa.String(length=10), nullable=False, comment='Difusora'),
    sa.Column('politica_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False, comment='Fecha de programación'),
    sa.Column('reloj_id', sa.Integer(), nullable=True),
    sa.Column('evento_reloj_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evento_reloj_id'], ['eventos_reloj.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['politica_id'], ['politicas_programacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reloj_id'], ['relojes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_programacion_fecha_difusora', 'programacion', ['fecha', 'difusora'], unique=False)
    op.create_index(op.f('ix_programacion_id'), 'programacion', ['id'], unique=False)
    op.create_index('ix_programacion_politica', 'programacion', ['politica_id'], unique=False)
    op.create_index('ix_programacion_reloj', 'programacion', ['reloj_id'], unique=False)
    # op.drop_table('politica_categorias')  # Tabla no existe
    op.add_column('dias_modelo', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_dias_modelo_difusora'), 'dias_modelo', ['difusora'], unique=False)
    op.add_column('eventos_reloj', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('eventos_reloj', 'orden',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('eventos_reloj', 'duracion',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'00:00:00'::character varying"))
    op.alter_column('eventos_reloj', 'descripcion',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('eventos_reloj', 'caracteristica_especifica')
    op.drop_column('eventos_reloj', 'desde_etm')
    op.drop_column('eventos_reloj', 'categorias_usar')
    op.drop_column('eventos_reloj', 'twofer_valor')
    op.drop_column('eventos_reloj', 'categoria_media')
    op.drop_column('eventos_reloj', 'offset_final')
    op.drop_column('eventos_reloj', 'caracteristica')
    op.drop_column('eventos_reloj', 'numero_cancion')
    op.drop_column('eventos_reloj', 'clasificaciones_evento_especifica')
    op.drop_column('eventos_reloj', 'grupos_reglas_ignorar')
    op.drop_column('eventos_reloj', 'todas_categorias')
    op.drop_column('eventos_reloj', 'usar_todas_categorias')
    op.drop_column('eventos_reloj', 'id_media')
    op.drop_column('eventos_reloj', 'tipo_etm')
    op.drop_column('eventos_reloj', 'grupos_reglas_ignorar_especifica')
    op.drop_column('eventos_reloj', 'desde_corte')
    op.drop_column('eventos_reloj', 'clasificaciones_evento')
    op.drop_column('eventos_reloj', 'categorias_usar_especifica')
    op.drop_column('eventos_reloj', 'comando_das')
    op.drop_column('eventos_reloj', 'sin_categorias')
    op.drop_column('eventos_reloj', 'valor_deseado')
    op.add_column('politicas_programacion', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('politicas_programacion_clave_key', 'politicas_programacion', type_='unique')
    op.create_index(op.f('ix_politicas_programacion_clave'), 'politicas_programacion', ['clave'], unique=True)
    op.create_index(op.f('ix_politicas_programacion_difusora'), 'politicas_programacion', ['difusora'], unique=False)
    op.drop_column('politicas_programacion', 'modificacion')
    op.drop_column('politicas_programacion', 'nombre')
    op.drop_column('politicas_programacion', 'alta')
    op.drop_column('politicas_programacion', 'descripcion')
    # Operaciones de reglas eliminadas - se eliminará la tabla completa
    op.add_column('relojes', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('relojes', 'nombre',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('relojes', 'duracion',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               nullable=False,
               existing_server_default=sa.text("'00:00:00'::character varying"))
    op.drop_constraint('relojes_clave_key', 'relojes', type_='unique')
    op.create_index(op.f('ix_relojes_clave'), 'relojes', ['clave'], unique=True)
    op.drop_column('relojes', 'grupo')
    op.drop_column('relojes', 'con_evento')
    op.drop_column('relojes', 'numero_regla')
    op.alter_column('relojes_dia_modelo', 'orden',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    
    # Eliminar tablas de sets de reglas y reglas al final
    op.drop_index('ix_reglas_id', table_name='reglas')
    op.drop_table('reglas')
    op.drop_index('ix_sets_reglas_id', table_name='sets_reglas')
    op.drop_table('sets_reglas')
    op.drop_index('ix_orden_asignacion_id', table_name='orden_asignacion')
    op.drop_table('orden_asignacion')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relojes_dia_modelo', 'orden',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('relojes', sa.Column('numero_regla', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('relojes', sa.Column('con_evento', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('relojes', sa.Column('grupo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_relojes_clave'), table_name='relojes')
    op.create_unique_constraint('relojes_clave_key', 'relojes', ['clave'])
    op.alter_column('relojes', 'duracion',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'00:00:00'::character varying"))
    op.alter_column('relojes', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('relojes', 'updated_at')
    op.add_column('reglas', sa.Column('orden', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('reglas', sa.Column('parametros', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('reglas', sa.Column('habilitada', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reglas', type_='foreignkey')
    op.create_foreign_key('reglas_set_regla_id_fkey', 'reglas', 'sets_reglas', ['set_regla_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reglas', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('reglas', 'updated_at')
    op.drop_column('reglas', 'habilitado')
    op.drop_column('reglas', 'valor')
    op.add_column('politicas_programacion', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('politicas_programacion', sa.Column('alta', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('politicas_programacion', sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('politicas_programacion', sa.Column('modificacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_politicas_programacion_difusora'), table_name='politicas_programacion')
    op.drop_index(op.f('ix_politicas_programacion_clave'), table_name='politicas_programacion')
    op.create_unique_constraint('politicas_programacion_clave_key', 'politicas_programacion', ['clave'])
    op.drop_column('politicas_programacion', 'updated_at')
    op.add_column('eventos_reloj', sa.Column('valor_deseado', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('sin_categorias', sa.VARCHAR(length=10), server_default=sa.text("'-'::character varying"), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('comando_das', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('categorias_usar_especifica', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('clasificaciones_evento', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('desde_corte', sa.VARCHAR(length=10), server_default=sa.text("'00:00:00'::character varying"), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('grupos_reglas_ignorar_especifica', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('tipo_etm', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('id_media', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('usar_todas_categorias', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('todas_categorias', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('grupos_reglas_ignorar', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('clasificaciones_evento_especifica', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('numero_cancion', sa.VARCHAR(length=10), server_default=sa.text("'-'::character varying"), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('caracteristica', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('offset_final', sa.VARCHAR(length=10), server_default=sa.text("'00:00:00'::character varying"), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('categoria_media', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('twofer_valor', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('categorias_usar', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('desde_etm', sa.VARCHAR(length=10), server_default=sa.text("'00:00:00'::character varying"), autoincrement=False, nullable=True))
    op.add_column('eventos_reloj', sa.Column('caracteristica_especifica', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('eventos_reloj', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('eventos_reloj', 'duracion',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'00:00:00'::character varying"))
    op.alter_column('eventos_reloj', 'orden',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('eventos_reloj', 'updated_at')
    op.drop_index(op.f('ix_dias_modelo_difusora'), table_name='dias_modelo')
    op.drop_column('dias_modelo', 'updated_at')
    op.create_table('politica_categorias',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('politica_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoria_nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='politica_categorias_pkey'),
    sa.UniqueConstraint('politica_id', 'categoria_nombre', name='politica_categorias_politica_id_categoria_nombre_key')
    )
    op.create_table('orden_asignacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('politica_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('parametros', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('habilitado', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['politica_id'], ['politicas_programacion.id'], name='orden_asignacion_politica_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='orden_asignacion_pkey')
    )
    op.create_index('ix_orden_asignacion_id', 'orden_asignacion', ['id'], unique=False)
    op.create_table('sets_reglas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('politica_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('habilitado', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('orden', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['politica_id'], ['politicas_programacion.id'], name='sets_reglas_politica_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sets_reglas_pkey')
    )
    op.create_index('ix_sets_reglas_id', 'sets_reglas', ['id'], unique=False)
    op.drop_index('ix_programacion_reloj', table_name='programacion')
    op.drop_index('ix_programacion_politica', table_name='programacion')
    op.drop_index(op.f('ix_programacion_id'), table_name='programacion')
    op.drop_index('ix_programacion_fecha_difusora', table_name='programacion')
    op.drop_table('programacion')
    op.drop_index(op.f('ix_set_reglas_id'), table_name='set_reglas')
    op.drop_table('set_reglas')
    # ### end Alembic commands ###
