"""add_reglas_and_separaciones_tables

Revision ID: 51dd1aa05223
Revises: 3e8b91ae54a5
Create Date: 2025-10-29 11:19:53.168514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51dd1aa05223'
down_revision = '3e8b91ae54a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reglas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politica_id', sa.Integer(), nullable=False),
    sa.Column('tipo_regla', sa.String(length=100), nullable=False),
    sa.Column('caracteristica', sa.String(length=100), nullable=False),
    sa.Column('tipo_separacion', sa.String(length=50), nullable=False),
    sa.Column('horario', sa.Boolean(), nullable=True),
    sa.Column('solo_verificar_dia', sa.Boolean(), nullable=True),
    sa.Column('habilitada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['politica_id'], ['politicas_programacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_id'), 'reglas', ['id'], unique=False)
    op.create_table('separaciones_regla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regla_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('separacion', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['regla_id'], ['reglas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_separaciones_regla_id'), 'separaciones_regla', ['id'], unique=False)
    op.drop_index('ix_set_reglas_id', table_name='set_reglas')
    op.drop_table('set_reglas')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('ix_grupos_usuarios_id', table_name='grupos_usuarios')
    op.drop_table('grupos_usuarios')
    op.drop_column('dias_modelo', 'updated_at')
    op.add_column('eventos_reloj', sa.Column('desde_etm', sa.String(length=10), nullable=True))
    op.add_column('eventos_reloj', sa.Column('desde_corte', sa.String(length=10), nullable=True))
    op.add_column('eventos_reloj', sa.Column('offset_final', sa.String(length=10), nullable=True))
    op.add_column('eventos_reloj', sa.Column('numero_cancion', sa.String(length=10), nullable=True))
    op.add_column('eventos_reloj', sa.Column('sin_categorias', sa.String(length=10), nullable=True))
    op.add_column('eventos_reloj', sa.Column('id_media', sa.String(length=50), nullable=True))
    op.add_column('eventos_reloj', sa.Column('categoria_media', sa.String(length=50), nullable=True))
    op.add_column('eventos_reloj', sa.Column('tipo_etm', sa.String(length=20), nullable=True))
    op.add_column('eventos_reloj', sa.Column('comando_das', sa.String(length=100), nullable=True))
    op.add_column('eventos_reloj', sa.Column('caracteristica', sa.String(length=50), nullable=True))
    op.add_column('eventos_reloj', sa.Column('twofer_valor', sa.String(length=50), nullable=True))
    op.add_column('eventos_reloj', sa.Column('todas_categorias', sa.Boolean(), nullable=True))
    op.add_column('eventos_reloj', sa.Column('categorias_usar', sa.Text(), nullable=True))
    op.add_column('eventos_reloj', sa.Column('grupos_reglas_ignorar', sa.Text(), nullable=True))
    op.add_column('eventos_reloj', sa.Column('clasificaciones_evento', sa.Text(), nullable=True))
    op.add_column('eventos_reloj', sa.Column('caracteristica_especifica', sa.String(length=50), nullable=True))
    op.add_column('eventos_reloj', sa.Column('valor_deseado', sa.String(length=50), nullable=True))
    op.add_column('eventos_reloj', sa.Column('usar_todas_categorias', sa.Boolean(), nullable=True))
    op.add_column('eventos_reloj', sa.Column('categorias_usar_especifica', sa.Text(), nullable=True))
    op.add_column('eventos_reloj', sa.Column('grupos_reglas_ignorar_especifica', sa.Text(), nullable=True))
    op.add_column('eventos_reloj', sa.Column('clasificaciones_evento_especifica', sa.Text(), nullable=True))
    op.alter_column('eventos_reloj', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('eventos_reloj', 'duracion',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'00:00:00'::character varying"))
    op.alter_column('eventos_reloj', 'orden',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('eventos_reloj', 'updated_at')
    # Agregar columna nombre como nullable primero
    op.add_column('politicas_programacion', sa.Column('nombre', sa.String(length=200), nullable=True))
    # Actualizar registros existentes con un valor por defecto
    op.execute("UPDATE politicas_programacion SET nombre = 'Política ' || id WHERE nombre IS NULL")
    # Ahora hacer la columna NOT NULL
    op.alter_column('politicas_programacion', 'nombre', nullable=False)
    op.add_column('politicas_programacion', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('politicas_programacion', sa.Column('categorias_seleccionadas', sa.Text(), nullable=True, comment='IDs de categorías separados por comas'))
    op.add_column('politicas_programacion', sa.Column('lunes', sa.Integer(), nullable=True))
    op.add_column('politicas_programacion', sa.Column('martes', sa.Integer(), nullable=True))
    op.add_column('politicas_programacion', sa.Column('miercoles', sa.Integer(), nullable=True))
    op.add_column('politicas_programacion', sa.Column('jueves', sa.Integer(), nullable=True))
    op.add_column('politicas_programacion', sa.Column('viernes', sa.Integer(), nullable=True))
    op.add_column('politicas_programacion', sa.Column('sabado', sa.Integer(), nullable=True))
    op.add_column('politicas_programacion', sa.Column('domingo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'politicas_programacion', 'dias_modelo', ['jueves'], ['id'])
    op.create_foreign_key(None, 'politicas_programacion', 'dias_modelo', ['sabado'], ['id'])
    op.create_foreign_key(None, 'politicas_programacion', 'dias_modelo', ['martes'], ['id'])
    op.create_foreign_key(None, 'politicas_programacion', 'dias_modelo', ['lunes'], ['id'])
    op.create_foreign_key(None, 'politicas_programacion', 'dias_modelo', ['domingo'], ['id'])
    op.create_foreign_key(None, 'politicas_programacion', 'dias_modelo', ['miercoles'], ['id'])
    op.create_foreign_key(None, 'politicas_programacion', 'dias_modelo', ['viernes'], ['id'])
    op.add_column('programacion', sa.Column('dia_modelo_id', sa.Integer(), nullable=True, comment='Día modelo usado para generar la programación'))
    op.create_foreign_key(None, 'programacion', 'dias_modelo', ['dia_modelo_id'], ['id'], ondelete='CASCADE')
    op.drop_column('relojes', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relojes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'programacion', type_='foreignkey')
    op.drop_column('programacion', 'dia_modelo_id')
    op.drop_constraint(None, 'politicas_programacion', type_='foreignkey')
    op.drop_constraint(None, 'politicas_programacion', type_='foreignkey')
    op.drop_constraint(None, 'politicas_programacion', type_='foreignkey')
    op.drop_constraint(None, 'politicas_programacion', type_='foreignkey')
    op.drop_constraint(None, 'politicas_programacion', type_='foreignkey')
    op.drop_constraint(None, 'politicas_programacion', type_='foreignkey')
    op.drop_constraint(None, 'politicas_programacion', type_='foreignkey')
    op.drop_column('politicas_programacion', 'domingo')
    op.drop_column('politicas_programacion', 'sabado')
    op.drop_column('politicas_programacion', 'viernes')
    op.drop_column('politicas_programacion', 'jueves')
    op.drop_column('politicas_programacion', 'miercoles')
    op.drop_column('politicas_programacion', 'martes')
    op.drop_column('politicas_programacion', 'lunes')
    op.drop_column('politicas_programacion', 'categorias_seleccionadas')
    op.drop_column('politicas_programacion', 'descripcion')
    op.drop_column('politicas_programacion', 'nombre')
    op.add_column('eventos_reloj', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('eventos_reloj', 'orden',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('eventos_reloj', 'duracion',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'00:00:00'::character varying"))
    op.alter_column('eventos_reloj', 'descripcion',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('eventos_reloj', 'clasificaciones_evento_especifica')
    op.drop_column('eventos_reloj', 'grupos_reglas_ignorar_especifica')
    op.drop_column('eventos_reloj', 'categorias_usar_especifica')
    op.drop_column('eventos_reloj', 'usar_todas_categorias')
    op.drop_column('eventos_reloj', 'valor_deseado')
    op.drop_column('eventos_reloj', 'caracteristica_especifica')
    op.drop_column('eventos_reloj', 'clasificaciones_evento')
    op.drop_column('eventos_reloj', 'grupos_reglas_ignorar')
    op.drop_column('eventos_reloj', 'categorias_usar')
    op.drop_column('eventos_reloj', 'todas_categorias')
    op.drop_column('eventos_reloj', 'twofer_valor')
    op.drop_column('eventos_reloj', 'caracteristica')
    op.drop_column('eventos_reloj', 'comando_das')
    op.drop_column('eventos_reloj', 'tipo_etm')
    op.drop_column('eventos_reloj', 'categoria_media')
    op.drop_column('eventos_reloj', 'id_media')
    op.drop_column('eventos_reloj', 'sin_categorias')
    op.drop_column('eventos_reloj', 'numero_cancion')
    op.drop_column('eventos_reloj', 'offset_final')
    op.drop_column('eventos_reloj', 'desde_corte')
    op.drop_column('eventos_reloj', 'desde_etm')
    op.add_column('dias_modelo', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_table('grupos_usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='grupos_usuarios_pkey')
    )
    op.create_index('ix_grupos_usuarios_id', 'grupos_usuarios', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('grupo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usuarios_pkey'),
    sa.UniqueConstraint('email', name='usuarios_email_key'),
    sa.UniqueConstraint('username', name='usuarios_username_key')
    )
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_table('set_reglas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('habilitado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='set_reglas_pkey')
    )
    op.create_index('ix_set_reglas_id', 'set_reglas', ['id'], unique=False)
    op.drop_index(op.f('ix_separaciones_regla_id'), table_name='separaciones_regla')
    op.drop_table('separaciones_regla')
    op.drop_index(op.f('ix_reglas_id'), table_name='reglas')
    op.drop_table('reglas')
    # ### end Alembic commands ###
