"""Add cortes table

Revision ID: 7b67a9436371
Revises: b16b4485bb6f
Create Date: 2025-10-06 10:56:23.048226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b67a9436371'
down_revision = 'b16b4485bb6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
