"""Add cortes table

Revision ID: 9dbaafd9a28f
Revises: 7b67a9436371
Create Date: 2025-10-06 10:57:01.184754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbaafd9a28f'
down_revision = '7b67a9436371'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cortes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion', sa.String(length=8), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cortes_id'), 'cortes', ['id'], unique=False)
    op.create_index(op.f('ix_cortes_nombre'), 'cortes', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cortes_nombre'), table_name='cortes')
    op.drop_index(op.f('ix_cortes_id'), table_name='cortes')
    op.drop_table('cortes')
    # ### end Alembic commands ###
