"""Initial migration

Revision ID: b16b4485bb6f
Revises: 
Create Date: 2025-10-05 23:10:36.700591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b16b4485bb6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('clasificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clasificaciones_id'), 'clasificaciones', ['id'], unique=False)
    op.create_table('conjuntos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conjuntos_id'), 'conjuntos', ['id'], unique=False)
    op.create_table('dayparts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('hora_inicio', sa.String(length=5), nullable=True),
    sa.Column('hora_fin', sa.String(length=5), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dayparts_id'), 'dayparts', ['id'], unique=False)
    op.create_table('grupos_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_usuarios_id'), 'grupos_usuarios', ['id'], unique=False)
    op.create_table('interpretes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interpretes_id'), 'interpretes', ['id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('apellido', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_table('sellos_discograficos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sellos_discograficos_id'), 'sellos_discograficos', ['id'], unique=False)
    op.create_table('tipos_clasificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_clasificacion_id'), 'tipos_clasificacion', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('apellido', sa.String(length=200), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('canciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('artista', sa.String(length=200), nullable=True),
    sa.Column('album', sa.String(length=200), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('conjunto_id', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['conjunto_id'], ['conjuntos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canciones_id'), 'canciones', ['id'], unique=False)
    op.create_table('movimientos_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_origen_id', sa.Integer(), nullable=True),
    sa.Column('categoria_destino_id', sa.Integer(), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_destino_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['categoria_origen_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_categorias_id'), 'movimientos_categorias', ['id'], unique=False)
    op.drop_table('calendarizacion_pautas')
    op.drop_table('rotaciones')
    op.drop_table('contratos')
    op.drop_table('pautas')
    op.drop_table('cartuchos')
    op.create_index(op.f('ix_dias_modelo_id'), 'dias_modelo', ['id'], unique=False)
    op.create_index(op.f('ix_difusoras_id'), 'difusoras', ['id'], unique=False)
    op.create_unique_constraint(None, 'difusoras', ['siglas'])
    op.create_index(op.f('ix_eventos_reloj_id'), 'eventos_reloj', ['id'], unique=False)
    op.alter_column('orden_asignacion', 'parametros',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_orden_asignacion_id'), 'orden_asignacion', ['id'], unique=False)
    op.create_index(op.f('ix_politicas_programacion_id'), 'politicas_programacion', ['id'], unique=False)
    op.alter_column('reglas', 'parametros',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_reglas_id'), 'reglas', ['id'], unique=False)
    op.create_index(op.f('ix_relojes_id'), 'relojes', ['id'], unique=False)
    op.drop_constraint('relojes_dia_modelo_dia_modelo_id_reloj_id_key', 'relojes_dia_modelo', type_='unique')
    op.create_index(op.f('ix_relojes_dia_modelo_id'), 'relojes_dia_modelo', ['id'], unique=False)
    op.create_index(op.f('ix_sets_reglas_id'), 'sets_reglas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sets_reglas_id'), table_name='sets_reglas')
    op.drop_index(op.f('ix_relojes_dia_modelo_id'), table_name='relojes_dia_modelo')
    op.create_unique_constraint('relojes_dia_modelo_dia_modelo_id_reloj_id_key', 'relojes_dia_modelo', ['dia_modelo_id', 'reloj_id'])
    op.drop_index(op.f('ix_relojes_id'), table_name='relojes')
    op.drop_index(op.f('ix_reglas_id'), table_name='reglas')
    op.alter_column('reglas', 'parametros',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_politicas_programacion_id'), table_name='politicas_programacion')
    op.drop_index(op.f('ix_orden_asignacion_id'), table_name='orden_asignacion')
    op.alter_column('orden_asignacion', 'parametros',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_eventos_reloj_id'), table_name='eventos_reloj')
    op.drop_constraint(None, 'difusoras', type_='unique')
    op.drop_index(op.f('ix_difusoras_id'), table_name='difusoras')
    op.drop_index(op.f('ix_dias_modelo_id'), table_name='dias_modelo')
    op.create_table('cartuchos',
    sa.Column('id_cartucho', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('cartucho_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id_media', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('referencia', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('referencia_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duracion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_cliente', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_agente', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_agencia', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fecha_pedido', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('descripcion_pedido', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_pedido', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio_vigencia', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_fin_vigencia', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('archivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('fecha_alta', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('habilitado', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_cartucho', name='cartuchos_pkey')
    )
    op.create_table('pautas',
    sa.Column('id_pauta', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('id_contrato', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_tipo_pauta', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_tipo_spot', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_difusora', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_concepto', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_politica_venta', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('comision_agente', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('comision_agencia', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('fecha_inicial', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_final', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('producto_anunciado', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('producto_relacionado', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('descripcion_campana', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('precio_por_spot', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('cartuchos_seleccionados', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('texto_factura_1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('texto_factura_2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), server_default=sa.text("'activo'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_pauta', name='pautas_pkey')
    )
    op.create_table('contratos',
    sa.Column('id_contrato', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('numero_contrato', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id_cliente', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_agente', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_agencia', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_tipo_contrato', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id_concepto_contrato', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicial', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_final', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), server_default=sa.text("'activo'::character varying"), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_contrato', name='contratos_pkey')
    )
    op.create_table('rotaciones',
    sa.Column('id_rotacion', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('id_pauta', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id_cartucho', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tipo_rotacion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('numero_versiones', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('letra', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('sustituir_versiones', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('usar_siguiente_rotacion', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_rotacion', name='rotaciones_pkey')
    )
    op.create_table('calendarizacion_pautas',
    sa.Column('id_calendarizacion', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('id_pauta', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hora_inicial', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('hora_final', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('spots_pedidos', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('cartuchos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('monto', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_calendarizacion', name='calendarizacion_pautas_pkey')
    )
    op.drop_index(op.f('ix_movimientos_categorias_id'), table_name='movimientos_categorias')
    op.drop_table('movimientos_categorias')
    op.drop_index(op.f('ix_canciones_id'), table_name='canciones')
    op.drop_table('canciones')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_clasificacion_id'), table_name='tipos_clasificacion')
    op.drop_table('tipos_clasificacion')
    op.drop_index(op.f('ix_sellos_discograficos_id'), table_name='sellos_discograficos')
    op.drop_table('sellos_discograficos')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_interpretes_id'), table_name='interpretes')
    op.drop_table('interpretes')
    op.drop_index(op.f('ix_grupos_usuarios_id'), table_name='grupos_usuarios')
    op.drop_table('grupos_usuarios')
    op.drop_index(op.f('ix_dayparts_id'), table_name='dayparts')
    op.drop_table('dayparts')
    op.drop_index(op.f('ix_conjuntos_id'), table_name='conjuntos')
    op.drop_table('conjuntos')
    op.drop_index(op.f('ix_clasificaciones_id'), table_name='clasificaciones')
    op.drop_table('clasificaciones')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
